### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dtch1997** [dtch1997/minigrid-language-experiments#1]
Decomposer
- [ ] Cost estimate for gpt-3.5-turbo
- [ ] Engineer working prompts for using oracle rewards (BabyAI instruction grammar) 
- [ ] Engineer working prompts for using LLM rewards

Rewarder
- [ ] Cost estimate for gpt-3.5-turbo
- [ ] Collect dataset of question-context-answer tuples
- [ ] Evaluate llama-7b on dataset (with few-shot examples?)
